name: Update submodules
on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update_submodules:
    name: Update submodules
    runs-on: ubuntu-18.04
    env:
      TZ: "Asia/Tokyo"
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Update submodules
      id: update
      run: |
        git clone --recurse-submodules https://github.com/kirin123kirin/template_cpp.git
        git clone --recurse-submodules https://github.com/kirin123kirin/template_pylib.git
        git clone --recurse-submodules https://github.com/kirin123kirin/template_python.git
        cd template_cpp && git submodule update --remote --recursive
        cd ../template_pylib && git submodule update --remote --recursive
        cd ../template_python && git submodule update --remote --recursive
        cd ..
    - name: Run git status
      id: status
      run: echo "::set-output name=status::$(git status -s)"
    - name: Add and commit files
      run: |
        git config --global user.email "kirin123kirin@gmail.com"
        git config --global user.name "kirin123"
        cd template_cpp && git commit -a -m "Update submodules at $(date "+DATE: %Y-%m-%d TIME: %H:%M:%S")" && git push
        cd ../template_pylib && git commit -a -m "Update submodules at $(date "+DATE: %Y-%m-%d TIME: %H:%M:%S")" && git push
        cd ../template_python && git commit -a -m "Update submodules at $(date "+DATE: %Y-%m-%d TIME: %H:%M:%S")" && git push
      if: ${{ steps.status.outputs.status }}
