name: Update submodules
on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update_submodules:
    name: Update submodules
    runs-on: ubuntu-18.04
    strategy: 
      matrix:
        repos: [ template_cpp, template_pylib, template_python ]
    env:
      TZ: "Asia/Tokyo"
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Update submodules
      id: update
      run: |
        git clone --recurse-submodules ${{ matrix.repos }}.git
        git -C ${{ matrix.repos }} submodule update --remote --recursive ${{ matrix.repos }}
    - name: Run git status
      id: status
      run: echo "::set-output name=status::$(git status -s)"
    - name: Add and commit files
      run: |
        git config --global user.email "kirin123kirin@gmail.com"
        git config --global user.name "kirin123"
        git -C ${{ matrix.repos }} commit -a -m "Update submodules at $(date "+DATE: %Y-%m-%d TIME: %H:%M:%S")"
        git -C ${{ matrix.repos }} push
      if: ${{ steps.status.outputs.status }}
